const columns = [
  {
    field: "number",
    headerName: "Order Number",
    flex: 1,
    minWidth: 50,
    editable: false,
  },
  {
    field: "itemName",
    headerName: "Item Name",
    flex: 1,
    minWidth: 50,
    editable: false,
  },
  {
    field: "code",
    headerName: "SKU",
    flex: 1,
    minWidth: 50,
    editable: false,
  },
  {
    field: "warehouseName",
    headerName: "Warehouse Name",
    flex: 1,
    minWidth: 50,
    editable: false,
  },
  {
    field: "clientName",
    headerName: "Client Name",
    flex: 1,
    minWidth: 50,
    editable: false,
  },
  {
    field: "date",
    headerName: "Date",
    flex: 1,
    minWidth: 50,
    editable: false,
  },
  {
    field: "open",
    headerName: "Open",
    flex: 1,
    minWidth: 50,
    editable: false,
  },
  {
    field: "received",
    headerName: "Received",
    flex: 1,
    minWidth: 50,
    editable: false,
  },
  {
    field: "onVA",
    headerName: "V.A.",
    flex: 1,
    minWidth: 50,
    editable: false,
  },
  {
    field: "onHold",
    headerName: "On Hold",
    flex: 1,
    minWidth: 50,
    editable: false,
  },
  {
    field: "onEmb",
    headerName: "embRel",
    flex: 1,
    minWidth: 50,
    editable: false,
  },
  {
    field: "invoiced",
    headerName: "Invoiced",
    flex: 1,
    minWidth: 50,
    editable: false,
  },
  // {
  //   field: "ordered",
  //   headerName: "Ordered",
  //   flex: 1,
  //   minWidth: 50,
  //   editable: false,
  //   hideable: false,
  // },
];

export default columns;
